[build]
buildCommand = "npm install && npx prisma generate"

[deploy]
startCommand = "npx prisma migrate deploy && node prisma/seed.js && node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
